### ISSUE TITLE
Sct widget doesn't refresh if you call "sct.update(...)"

### ISSUE THREAD

**Issue by Ilbasso-dot** [flintforge/awesome-wm-widgets#1]
It only change temperature of the screen, but not the widget number.

**Comment by flintforge** [comment]
update > get_temperature > update of sct.markup > 
This does update the widget indeed. 
`awesome -v `?

**Comment by Ilbasso-dot** [comment]
I apologize, I have used different session of Sct(), so they worked in parallel. Now it works.
